# Generated by Django 6.1.1 on 2026-09-15 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminventario',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('VENDIDO', 'Vendido'), ('ENVIADO', 'Enviado (simulación)')], default='DISPONIBLE', max_length=20),
        ),
    ]
