# Generated by Django 6.1.1 on 2026-09-15 00:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(choices=[('INICIAL', 'Inicial'), ('RECARGA', 'Recarga'), ('DEBITO', 'Debito'), ('VENTA', 'Venta de objeto')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='billetera',
            constraint=models.CheckConstraint(condition=models.Q(('saldo__gte', 0)), name='wallet_nonnegative_balance'),
        ),
    ]
